### ISSUE TITLE
RuntimeError: Failed to decode audio.

### ISSUE THREAD

**Issue by weru88097** [MingLunHan/CIF-HieraDist#1]
What is the reason for showing audio decoding error while extracting features? Please answer.
Traceback (most recent call last):
  File "../../examples/speech_to_text/prep_aishell1_data.py", line 358, in <module>
    main()
  File "../../examples/speech_to_text/prep_aishell1_data.py", line 354, in main
    process(args)
  File "../../examples/speech_to_text/prep_aishell1_data.py", line 266, in process
    for wav, sample_rate, _, spk_id, utt_id in tqdm(dataset):
  File "/home/weiyangjie/anaconda3/envs/fairseq/lib/python3.8/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "../../examples/speech_to_text/prep_aishell1_data.py", line 165, in __getitem__
    return load_aishell1_item(
  File "../../examples/speech_to_text/prep_aishell1_data.py", line 55, in load_aishell1_item
    waveform, sample_rate = torchaudio.load(file_audio)
  File "/home/weiyangjie/anaconda3/envs/fairseq/lib/python3.8/site-packages/torchaudio/_backend/utils.py", line 203, in load
    return backend.load(uri, frame_offset, num_frames, normalize, channels_first, format, buffer_size)
  File "/home/weiyangjie/anaconda3/envs/fairseq/lib/python3.8/site-packages/torchaudio/_backend/ffmpeg.py", line 334, in load
    return load_audio(os.path.normpath(uri), frame_offset, num_frames, normalize, channels_first, format)
  File "/home/weiyangjie/anaconda3/envs/fairseq/lib/python3.8/site-packages/torchaudio/_backend/ffmpeg.py", line 100, in load_audio
    return torch.ops.torchaudio.compat_load(src, format, filter, channels_first)
  File "/home/weiyangjie/anaconda3/envs/fairseq/lib/python3.8/site-packages/torch/_ops.py", line 692, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: Failed to decode audio.

**Comment by MingLunHan** [comment]
The problem arises during the process of loading audio with torchaudio, indicating that there might be an issue with the underlying dependencies of torchaudio. This repository has been successfully run by many people, so I suggest you first try loading audio using torchaudio separately to see if it's feasible. Particularly, check if torchaudio and PyTorch versions are compatible. If you still encounter issues, please contact me via email. @weru88097 You can find the version of all dependencies in requirements.txt. Thanks for your attention!
